server:
  port: 443

  ssl:
    enabled: true
    key-store: classpath:cert.jks
    key-password: seleuchel
    key-store-type: JKS
    key-alias: 1

    trust-store: classpath:trustcert.jks
    trust-store-password: seleuchel
    protocol: TLS
    client-auth: want

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2_db
  h2:
    console:
      path: /S@fE*20N3*6ON3
      enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
