server:
  port: 443
#  443
  ssl:
    enabled: true
    key-store: classpath:cert.jks
    key-password: seleuchel # 비밀번호 암호화 + 솔트 넣기
    key-store-type: JKS
    key-alias: 1

    trust-store: classpath:trustcert.jks
    trust-store-password: seleuchel # 비밀번호 암호화 + 솔트 넣기 + 솔트는 파일 불러오기.
    protocol: TLS
    client-auth: want

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:./h2_db

jasypt:
  encryptor:
    bean: keyEncryptor
#    password: test1234
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES
